name: Node.js CI

on:
  push:
    branches: [ "pro" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Yarn install...
      run: yarn install

    - name: Check if PM2 is installed
      run: |
        if ! command -v pm2 &> /dev/null
        then
            echo "PM2 could not be found, installing..."
            yarn global add pm2
        else
            echo "PM2 is already installed"
        fi

    - name: Start or Restart PM2 Application
      run: |        
        pm2 delete "api-smart-shop" || true
        pm2 start yarn --interpreter bash --name "api-smart-shop" -- build:production
        pm2 list  # Hiển thị danh sách các ứng dụng hiện đang được quản lý bởi PM2 (để kiểm tra/debug)
